spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/kiosk?useSSL=false
    username: bruni
    password: codeSquad123!

  sql:
    init:
      mode: always
